### ISSUE TITLE
Example for yieldElements 

### ISSUE THREAD

**Issue by paparga** [rjmac/aeson-streaming#1]
Hi Robert,

Maybe this library can solve our problem with parsing big JSON files, in our case it's about 350 MB and probably this size will be increasing.  Right now we are using two conduits, the first one is for reading and parsing our file and the second one is for processing and writing to another file. For us this means that the current Haskell program is using over more than 1 GB of memory and we think with yieldElements we can have only one conduit. But maybe we are wrong.

So first, is this correct? And also, can you provide us an example?

Thanks from Chile!

**Comment by rjmac** [comment]
I'd need to know more about what you're trying to do exactly, but if your use-case is basically "navigate to a point in the file and then produce the values at that point one by one", you'd want either `yieldArrayElementsAt` or `yieldObjectFieldsAt`.  Those are the main use-cases I had in mind when I wrote the library.  If you're doing something more complex, where you'd like a SAX-style stream of events, this library probably won't help you much I'm afraid.  There are very simple examples in the haddocks for both those functions in the conduits package.

**Comment by paparga** [comment]
I will make an example
``` haskell

-- Data structure of input.json
data InPerson = InPerson
  { firstName :: Text
  , lastName :: Text
  , birthDate :: Day
  ....
  } deriving (Show, Generic, ToJSON)

-- Data structure of output.csv
data OutPerson = OutPerson
  { fullName :: Text
  , age :: Int
  ...
  } deriving (Show, Generic, ToRecord)

-- And a function to transform 
toOutPerson :: InPerson -> OutPerson
```
So I need to read input.json, map each value and write to output.csv. 
My code looks like this right now.
``` haskell
readAndWrite :: IO ()
readAndWrite = do
   inputs <-   runResourceT $ runConduit ...
   -- also a conduit
   toOutput $ toOutPerson <$> inputs
```
So I have 2 conduits, using a lot of memory, and what I want is to have only one.
The function I think I need has this type annotation.  
``` haskell
yieldValue :: ConduitT ByteString Value m ()
```
The final code should look like this:
``` haskell
readAndWrite :: IO ()
readAndWrite = runResourceT $ runConduit 
    $ readInputsConduit
   .| yieldValue
   .| mapC toOutPerson
   .| toOutputConduit
``` 
So this library supports this? 
If not, how can I achieve it?

**Comment by rjmac** [comment]
Ah, yes, you can do something like that.  If your input is something like

```json
[
  {"firstName" : "Fred", "lastName": "Jones", "birthDate" : "2001-01-01", ...},
  ... a million others of those...
]
```

then it'd look something like

```haskell
import Data.Aeson.Streaming.Conduit (yieldArrayElementsAt)

readAndWrite :: IO ()
readAndWrite = runResourceT $ runConduit
   $ readInputsConduit -- this produces ByteStrings
  .| yieldArrayElementsAt [] -- "[]" means the array is at top level; there's no navigation necessary to find it
  .| mapC toOutPerson
  .| toOutputConduit
```

**Comment by paparga** [comment]
works great thanks!
